install: true
sudo: required
group: bluezone
language: ruby
rvm:
    - 2.5.3
branches:
 only:
   - master
services:
    - mongodb
    - redis-server
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - ./config/scripts/build/pull_request.sh
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
